### ISSUE TITLE
Fix alphabetical ordering in study drop down menu and study cards

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EbrcWebsiteCommon#123]
Our current ordering of studies in both the drop down menu and the cards (but not on the study summaries table) looks to be alphabetical, but if you look closer, you'll find that it's ordered first by capitalization status, then by alphabet. For instance, in the screenshot below, you can see that all studies starting with a capital P are grouped together, as expected, but "Preventing Congenital Syphilis", which has a lowercase r and e as the second and third letters is ordered after PROVIDE rather than before PRISM. We need to fix this ordering to be truly alphabetical, regardless of capitalization

<img width="490" alt="Screen Shot 2022-04-15 at 9 08 52 AM" src="https://user-images.githubusercontent.com/54597319/163581175-6a88ec16-b196-44eb-b757-40f0bd5f5c7f.png">

**Comment by jernestmyers** [comment]
Looks like we'll also need to strip the HTML, as evidenced by the position of the studies in the red box. 

Also, just to be sure: @SheenaTomko, are we okay with the prerelease studies getting tacked on at the end of the list (blue box)? As a guest or unauthorized user, they're differentiated with "(coming soon)" so it makes some sense. But I was confused when using my account that has access to all studies because they're no longer differentiated with "(coming soon)". Would this be a cause for confusion for folks that have access to one or more prerelease studies? Would it help to replace "(coming soon)" with "(prerelease)", which I have a vague memory of seeing before.

![Image](https://user-images.githubusercontent.com/69446567/202277912-ec84b4e7-fd73-4635-9054-7e5569eb3108.png)

**Comment by jernestmyers** [comment]
@SheenaTomko I've pushed a fix to this issue that's under review. In discussing this with the `ui-infra` team, we decided we'd prefer to sort this on the backend and have thus done so. As of now, there isn't a simple solution to "strip" the HTML in order to place the `SCORE S. Mansoni` studies in the correct order, but we think it's okay for now. 

There is one existing frontend sorting behavior that has been removed that I'm unsure of though. Production currently uses an `appearFirst` attribute according to the following code and justification:
```js
      // Our presenters use a build number of 0 to convey studies
      // which should appear first...
      // (1) in the cards and...
      // (2) in the "Search a study" menu
      if (record.attributes.build_number_introduced === '0') {
        records.appearFirst.add(record.attributes.dataset_id);
      }
```
Do you know if this is being used in any capacity? I removed the use of this attribute in the frontend sorting and I didn't notice any deviant sorting. Is this affecting user datasets perhaps? If so, my two dummy datasets are also sorting as I'd expect.

**Comment by jernestmyers** [comment]
Okay, thanks for the response. I'm going to merge work that removes the `appearFirst` logic, so let's just keep that in mind if we happen to notice any undesired behavior.

**Comment by SheenaTomko** [comment]
All looks good here!
