### ISSUE TITLE
Modify the data access restrictions popup

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EbrcWebsiteCommon#127]
Currently, the popup looks like this:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/25450900/169599383-ed67185d-01f5-46cd-878e-9ac5b161c2d9.png">

Please change:
`Please acquire research approval in order to download data. The data from this study requires approval to download and use in research projects.`

to:
`This study requires you to submit an access request and get approval from the study team before downloading data.` 

Also we don't like that there are two buttons for log in and Submit data access request. you need to log in to submit the request, so you're not choosing to do one or the other, you're doing both in sequence. Currently, if you are not logged on and click the "submit data access request" button, you are directed to the login page anyway. Please replace these 2 buttons with 1 button that says `Log In or Submit Data Access Request`

**Comment by jernestmyers** [comment]
I have a couple clarifying questions.

1. For controlled studies, do we still want to specify that data access will be granted upon submission (see screenshot)? If so, we could do `This study requires you to submit an access request. Data access will be granted immediately upon request submission.`
2. Would it be better to keep both buttons but disable the `Submit Data Access Request` button if the user isn't logged in? We could provide a tooltip that explains they must be logged in to submit a request. My thinking is that it is more explicit that the user will need to get back to the modal in order to submit a request. Plus, I feel it's more clear why the button routes the user to different places.

![Image](https://user-images.githubusercontent.com/69446567/202481033-0bb42a92-0ff5-4a6f-aaac-ee6ce666b96e.png)

**Comment by dmfalke** [comment]
I think the Login button is there in case the user already has access once logged in.

**Comment by jernestmyers** [comment]
Here are screenshots to better articulate what I propose.

1. Verbiage tweak for controlled studies
![image](https://user-images.githubusercontent.com/69446567/204841330-02a96349-3cfd-4cb1-b1cd-77307315b3a7.png)

2. Disabled button with Tooltip if user isn't logged in
![image](https://user-images.githubusercontent.com/69446567/204840387-f5992484-7957-4558-98e6-8de045c776bb.png)

**Comment by danicahelb** [comment]
Your ideas sound great @jernestmyers. 
One comment... if I am working in ClinEpi as a guest but do not have access to the study attached to my VeuPathDB account, the prompt will direct me to log in. After I log in, can I be auto-routed to the page to fill out the data access form? (ie, i don't want to log in via this prompt and then click on a download file and have to see this popup again)

**Comment by danicahelb** [comment]
![Image](https://user-images.githubusercontent.com/25450900/221006080-8fbf1bfb-4ac8-4b84-928a-3cfc7d1a06c4.png)

Really nice, clicking login immediately brings me to the access request form after I log in!

and the login button is not on the popup when i am logged in already:



![Image](https://user-images.githubusercontent.com/25450900/221006414-e28ca886-63b1-46b1-aa67-ee184f5fb970.png)
